# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0002_insert_init_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256)),
                ('display_name', models.CharField(max_length=256)),
                ('site', models.URLField(max_length=256)),
                ('logo_url', models.URLField(max_length=256, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasources', to='country.Country')),
            ],
        ),
    ]
