# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True)),
                ('type', models.SmallIntegerField(choices=[(0, 'android'), (1, 'ios'), (2, 'winphone')])),
                ('brand', models.CharField(max_length=128, null=True)),
                ('model', models.CharField(max_length=128, null=True)),
                ('os_version', models.CharField(max_length=128, null=True)),
                ('token', models.CharField(max_length=128, unique=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
