# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('region', '0002_insert_init_data'),
        ('retailer', '0002_insert_init_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('tel', models.CharField(max_length=32, null=True)),
                ('address', models.CharField(max_length=512, null=True)),
                ('working_time', models.CharField(max_length=512, null=True)),
                ('website', models.CharField(max_length=512, null=True)),
                ('email', models.CharField(max_length=128, null=True)),
                ('longitude', models.FloatField(null=True)),
                ('latitude', models.FloatField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='region.Region')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='retailer.Retailer')),
            ],
        ),
    ]
