# Generated by Django 2.0.1 on 2018-01-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('currency_code', models.CharField(db_index=True, max_length=4)),
                ('sign', models.CharField(max_length=4)),
            ],
        ),
    ]
