# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('currency_code', models.CharField(db_index=True, max_length=4)),
                ('sign', models.CharField(max_length=4)),
            ],
        ),
    ]
