# Generated by Django 2.0.1 on 2018-01-23 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0001_initial'),
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256)),
                ('display_name', models.CharField(max_length=256)),
                ('site', models.URLField(max_length=256, null=True)),
                ('logo_url', models.URLField(max_length=256, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retailers', to='country.Country')),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retailers', to='source.DataSource')),
            ],
        ),
        migrations.CreateModel(
            name='RetailerProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('value', models.CharField(blank=True, max_length=1024)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailer.Retailer')),
            ],
        ),
    ]
