# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 12:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0002_insert_init_data'),
        ('source', '0002_insert_init_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=256)),
                ('display_name', models.CharField(max_length=256)),
                ('site', models.URLField(null=True, max_length=256)),
                ('logo_url', models.URLField(max_length=256, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailers', to='country.Country')),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailers', to='source.DataSource')),
            ],
        ),
        migrations.CreateModel(
            name='RetailerProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('value', models.CharField(blank=True, max_length=1024)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retailer.Retailer')),
            ],
        ),
    ]
