# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, db_index=True)),
                ('display_name', models.CharField(max_length=256)),
                ('level', models.SmallIntegerField(null=False)),
                ('active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(null=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='category.Category')),
            ],
        ),
    ]
