# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('display_name', models.CharField(max_length=128)),
                ('active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='country.Country')),
                ('parent', models.ForeignKey(null=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sub_regions', to='region.Region')),
            ],
        ),
    ]
