
DEVICE_TYPE_ANDROID = 0
DEVICE_TYPE_IOS = 1
DEVICE_TYPE_WINPHONE = 2

DATASOURCE_ID_1_DAY_CO_NZ = 1
DATASOURCE_NAME_1_DAY_CO_NZ = '1-day.co.nz'
DATASOURCE_ID_GRABONE_CO_NZ = 2
DATASOURCE_NAME_GRABONE_CO_NZ = 'grabone.co.nz'
DATASOURCE_ID_LASOO_CO_NZ = 3
DATASOURCE_NAME_LASOO_CO_NZ = 'lasoo.co.nz'

RETAILER_FRESH_CHOICE = 1
RETAILER_SUPERVALUE = 2
RETAILER_NEW_WORLD = 3
RETAILER_PAKN_SAVE = 4
RETAILER_FOURSQUARE = 5
RETAILER_1_DAY_CO_NZ = 6

RETAILER_NAME_1_DAY_CO_NZ = DATASOURCE_NAME_1_DAY_CO_NZ
RETAILER_NAME_GRABONE_CO_NZ = DATASOURCE_NAME_GRABONE_CO_NZ
RETAILER_NAME_COUNTDOWN = 'countdown'
